server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wir
    username: wir
    password: wir
    driver-class-name: org.postgresql.Driver
# ===============================
# LIQUIBASE
# ===============================
  liquibase:
    user: wir
    password: wir
    change-log: classpath:liquibase/db/changelog/wir.xml
    url: jdbc:postgresql://localhost:5432/wir
  # ===============================
# JPA
# ===============================
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# ===============================
# SMTP EMAIL
# ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: whoisright2018@gmail.com
    password: Burekk23899
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ===============================
# LOGGING
# ===============================
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
# ===============================
# SPRING LOGIN
# ===============================
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1964708490466561
            clientSecret: 0892417fc2fb8f278e3c2179d2ccb6dd
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
